kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.20.46.237:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: "kube-system"
  pool: k8s
  userId: admin
  userSecretName: ceph-secret-user
